version: '2'

networks:
  matecat-network:
    driver: bridge

services:
  filters:
    build: ./MateCatFilters/
    container_name: docker_matecat_filter
    expose:
      - 8732
    networks:
       - matecat-network

  redis:
    image: redis
    expose:
      - 6379
    networks:
       - matecat-network

  amq:
    image: webcenter/activemq:latest
    expose:
      - 61613
      - 61616
      - 8161
    networks:
       - matecat-network
       
  mysql:
    container_name: docker_mysql
    image: mysql/mysql-server:5.7
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: matecat
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
    networks:
      matecat-network:
        aliases:
          - mysql

  # mosesdecoder:
  #   build: ./Moses/
  #   expose:
  #    - 8000
  #   networks:
  #    - matecat-network

  matecat:
    build: ./MateCatApache/
    container_name: docker_matecat
    volumes:
      - ~/matecat:/var/www/matecat:rw
    ports:
      - 80
    networks:
       - matecat-network
    links:
      - mysql
      - redis
      - amq
      - filters
      # - mosesdecoder
